#!/bin/bash

#########################
#Install Dependencies	#
#########################

sudo pacman -S --noconfirm qtwebkit
sudo pacman -S --noconfirm phonon-qt4
sudo pacman -S --noconfirm quazip-qt4
sudo pacman -S --noconfirm qtkeychain-qt4
sudo pacman -S --noconfirm attica-qt4
sudo pacman -S --noconfirm liblastfm
sudo pacman -S --noconfirm libechonest
sudo pacman -S --noconfirm lucene++
sudo pacman -S --noconfirm qjson
sudo pacman -S --noconfirm qca

sudo pacman -S --noconfirm cmake
sudo pacman -S --noconfirm sparsehash
sudo pacman -S --noconfirm boost
sudo pacman -S --noconfirm websocketpp


#########################
#Remove Configuration	#
#########################


rm -R /usr/share/backgrounds
rm -R /usr/share/gnome-background-properties

#########################
#Womba Function		#
#########################

function womba {

git clone https://github.com/womba/$1 /tmp/$1
cp -R /tmp/$1/* /
rm -R /tmp/$1

}

#########################
#Install Packages	#
#########################

womba womba
womba telegram
womba desktop-default
womba icons-shadowless
womba rune-core
womba rune-app-folder
womba rune-app-folder-plus
womba rune-bash-profile
womba rune-terminal-color
womba rune-wallpaper

systemctl enable runecore.service

