#!/bin/bash

#########################
#Install Dependencies	#
#########################

pacman -S --noconfirm qtwebkit
pacman -S --noconfirm phonon-qt4
pacman -S --noconfirm attica-qt4
pacman -S --noconfirm liblastfm
pacman -S --noconfirm libechonest
pacman -S --noconfirm lucene++
pacman -S --noconfirm qjson
pacman -S --noconfirm qca

pacman -S --noconfirm cmake
pacman -S --noconfirm sparsehash
pacman -S --noconfirm boost
pacman -S --noconfirm websocketpp


#########################
#Remove Configuration	#
#########################


rm -R /usr/share/backgrounds
rm -R /usr/share/gnome-background-properties

#########################
#Womba Function		#
#########################

function womba {

git clone https://github.com/womba/$1 /tmp/$1
cp -R /tmp/$1/* /
rm -R /tmp/$1

}

#########################
#Install Packages	#
#########################

womba womba
womba telegram
womba icons-shadowless
womba rune-core
womba rune-app-folder
womba rune-app-folder-plus
womba rune-bash-profile
womba rune-terminal-color
womba rune-wallpaper
womba qtkeychain-qt4
womba quazip-qt4
womba tomahawk
womba firefox-ublock
womba desktop-default
womba dash-to-dock
womba rune-gnome-extensions

systemctl enable runecore.service

