#!/bin/bash


#########################
#Remove Configuration	#
#########################


#rm -R /usr/share/backgrounds
#rm -R /usr/share/gnome-background-properties

#########################
#Womba Function		#
#########################

function womba {

git clone https://github.com/womba/$1 -b testing /tmp/$1
cp -R /tmp/$1/* /
rm -R /tmp/$1

}

#########################
#Install Packages	#
#########################

womba womba
womba telegram
womba icons-shadowless
womba rune-core
womba rune-sounds
womba rune-app-folder
womba rune-app-folder-plus
womba rune-bash-profile
womba rune-terminal-color
#womba rune-wallpaper
womba firefox-ublock
womba desktop-default
womba dash-to-dock
womba rune-gnome-extensions
womba rune-dash-settings
womba gnome-top-left-corner
womba gnome-topicons
womba gnome-impatience

systemctl enable runecore.service

